baseURL: "http://localhost:1313"
title: Alcorques con rejilla
theme: hugo-theme-console
languageCode: es
taxonomies:
  tag: tags
  category: categories
params:
  animateStyle: animated zoomIn fast
  navlinks:
    - name: "acerca de"
      url: "acerca-de"
    - name: "artículos"
      url: "articulos"
    - name: "galería"
      url: "galeria"
  titleCutting: yes
markup:
  goldmark:
    renderer:
      unsafe: true
